#운영서버에 올리기전 테스트 환경
#적용방법 : VM 옵션 값에 추가 "-Dspring.profiles.active=dev"

server:
  port: 8081


spring:
  datasource:
    url: jdbc:log4jdbc:postgresql://localhost:5432/postgres
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: postgres
    password: 1234