#운영서버에 올리기전 테스트 환경
#적용방법 : VM 옵션 값에 추가 "-Dspring.profiles.active=dev"

server:
  port: 8081
  servlet:
    context-path: /api


spring:
  datasource:
    username: postgres
    password: 1234

    #url: jdbc:postgresql://localhost:5432/postgres
    #driver-class-name: org.postgresql.Driver
    url: jdbc:log4jdbc:postgresql://localhost:5432/postgres
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    hikari:
      maximum-pool-size: 3
    dbcp2:
      default-schema: api

# 이걸 안해주니
logging:
  log4j2:
    config:
      override:
        - src/main/resources/log4j2-dev.yaml


mybatis:
  mapper-locations:
    - mybatis/mapper/*.xml
  type-aliases-package: com.spring.ref.model
  configuration:
    map-underscore-to-camel-case: true